<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017\12\18 0018
 * Time: 10:47
 */

namespace app\user\home;

use app\user\model\home\PrivilegeGroup;
use app\user\model\home\User;

class BecomeMember extends Common
{


    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){

        if(request()->isGet()){
            $get_data = request()->param();
            //查询相应会员价格
            if(isset($get_data['price_type'])){
                $re = PrivilegeGroup::where('p.id',$get_data['id'])
                    ->alias('p')
                    ->join('dp_user u','u.group_id = p.id','LEFT')
                    ->field("p.id,p.group_name,p.".$get_data['price_type'])
                    ->field('count(u.id) as people_num')
                    ->find();
               // var_dump($re->getLastSql());exit;
                $this->assign('data',$re);
                $this->assign('price',$re[$get_data['price_type']]);
                $this->assign('price_type',$get_data['price_type']);
                //查询属于当前会员人数  通过积分点数判断

                //系统设置每个积分为充值或者升级会员金额总数
            }else{
                $re = PrivilegeGroup::where('id',$get_data['id'])->value($get_data['price_type']);
            }
        }

       //$this->assign('member_group',(new PrivilegeGroup())->sel_need_fee());


        $this->view->engine->layout(false);

        return $this->fetch();

    }



    /*
     * 成为会员可选择的列表页面
     * */

    public function member_list(){


        $member_info = User::where('id',UID)->field('id,nickname,head_img,is_bind_phone,real_name')->find();

        if(request()->isAjax()){
            if(!$member_info->real_name || !$member_info->is_bind_phone){
                return json(array('code'=>103,'msg'=>'请完成真实姓名和绑定手机'));
            }
        }
        if(!$member_info->real_name || !$member_info->is_bind_phone){
            //不满足条件直接跳转
            $this->redirect('user/index/index');
        }
        $this->assign('member_info',$member_info);
        $this->assign('member_group',(new PrivilegeGroup())->sel_need_fee());
          //var_dump((new PrivilegeGroup())->sel_need_fee());  exit;
        $this->view->engine->layout(false);
            return $this->fetch();
    }

}
