<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017\12\23 0023
 * Time: 10:05
 */

namespace app\user\home;

use app\index\controller\Home;
/*
 * 前台公共控制器
 *
 * */
use app\user\model\home\UpgradeMember;
use app\user\model\home\Recharge;
use think\Db;
class Common extends Home
{

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        // 判断是否登录，并定义用户ID常量
        defined('UID') or define('UID', $this->isLogin());
       /* $map = ['uid'=>UID,'read_status'=>0];
        //查询用户消息数量
        $Upgrade_news_num = UpgradeMember::where($map)->count();
        $Recharge_news_num = Recharge::where($map)->count();

        //查询用户与伴游的消息数量 ,在此不构造用户消息参数,只加上数量即可
        $chat_num = Db::name('chat_content_date')->where(['receive_uid'=>UID,'read_status'=>0])->count();

        if($Upgrade_news_num || $Recharge_news_num || $chat_num){
              $data_no_read = array();

              $data_no_read['url_sql'] = '';
              //构造连接参数
              if($Upgrade_news_num)   $data_no_read['url_sql'] .= $data_no_read['url_sql'] ? '&UpgradeMember='.$Upgrade_news_num : '?UpgradeMember='.$Upgrade_news_num;

              if($Recharge_news_num)  $data_no_read['url_sql'] .= $data_no_read['url_sql'] ? '&Recharge='.$Recharge_news_num : '?Recharge='.$Recharge_news_num;;

              $data_no_read['all_num'] = $Upgrade_news_num+$Recharge_news_num+$chat_num;

              $this->assign('all_news_num',$data_no_read);
        }*/
    }


    /**
     * 检查是否登录，没有登录则跳转到登录页面
     * @return int
     */
    final protected function isLogin()
    {
        // 判断是否登录
        if ($uid = is_member_signin()) {
            // 已登录
            return $uid;
        } else {
            // 未登录
            $this->redirect('user/Login/index');
        }
    }

}