<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017\12\23 0023
 * Time: 10:05
 */

namespace app\user\home;

use app\index\controller\Home;
/*
 * 前台公共控制器
 *
 * */

class Common extends Home
{

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

}