<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017\12\23 0023
 * Time: 10:17
 */

namespace app\user\home;

use think\Controller;

use app\user\model\home\Login as LoginModel;

class Login extends Controller
{

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->assign('url_root',config('root_url'));
    }

    public function index(){

        if($this->request->isPost()){
            $model =new LoginModel;
            $data = request()->post();

            return $model->login($data['username'],$data['password']);
        }

        return $this->fetch();


    }


}