<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017\12\23 0023
 * Time: 10:17
 */

namespace app\user\home;

use think\Controller;

use app\user\model\home\Login as LoginModel;
use think\Session;

class Login extends Controller
{

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->assign('url_root',config('root_url'));
    }

    public function index(){

        if($this->request->isPost()){
            $model =new LoginModel;
            $data = request()->post();
            return $model->login($data['username'],$data['password'],$data['login_addr_x'],$data['login_addr_y']);
        }

        return $this->fetch();


    }

    /*
     * 退出登录
     * */

    public function login_out(){
        Session::delete('user_auth_home');
        Session::delete('user_auth_sign_home');
        $this->redirect('index/Index/index');
    }

}