<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017\12\15 0015
 * Time: 16:42
 */

namespace app\user\home;

use function foo\func;
use think\Controller;
use app\user\model\home\UpgradeMember;
use app\user\model\home\Recharge;
use think\Db;
class News extends Common
{


    public function _initialize()
    {

        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->assign('title','消息页面');
    }

    public function index(){

        //echo "<script>alert('".lang('Parse error')."')</script>";   //测试语言包助手函数
        //查询用户所有消费消息

        $model_name = array('Recharge','UpgradeMember');
        /*
         * @param $model_name  模型类名,url参数名
         * */
        $data = function($model_name = array()){
            $current_news_info = new \stdClass();
            foreach($model_name as $k=>$v){
                //未读数量
                $count_name = strtolower($v).'_num';
                $$count_name = request()->param($v)?request()->param($v):'';
                $info_name = strtolower($v).'_info';
                //类（模型）名
                $class_name = 'app\user\model\home\\'.class_basename($v);
                $$info_name = new \stdClass();
                $$info_name->$count_name = $$count_name ? $$count_name : 0;
                $$info_name->info_num = $class_name::where('uid',UID)->order('id desc')->count('id');
                $current_name = strtolower($v);
                $current_news_info->$current_name = $$info_name;
                //显示未读消息的最后一次时间
                $time_name = strtolower($v).'_time';
                $$info_name->$time_name = $class_name::where('uid',UID)->order('id desc')->value('create_time');
            }

            return $current_news_info;
        };

        $this->assign('data',$data($model_name));
        //var_dump($data($model_name));
        //查询用户伴游未读消息数量

        $chat_num = Db::name('chat_content_date')->where(['receive_uid'=>UID,'read_status'=>0])->count();

        //传递用户信息
        $chat_res= array();
        if($chat_num){
            //查询所有信息
            $chat_res = Db::name('chat_content_date')
                        ->alias('c')
                        ->join('__USER__ u','u.id = c.send_uid','LEFT')
                        ->where(['receive_uid'=>UID,'read_status'=>0])
                        ->field('count(c.id) as cnum, c.receive_uid,c.content,c.send_uid,c.create_time,c.id,u.head_img,u.nickname')
                        ->order('c.create_time desc')
                        ->group('c.send_uid')
                        ->select();
        }else{
            $chat_res = Db::name('chat_content_date')
                ->alias('c')
                ->join('__USER__ u','u.id = c.send_uid','LEFT')
                ->where(['c.receive_uid'=>UID])
                ->field('c.receive_uid,c.content,c.send_uid,c.create_time,c.id,u.head_img,u.nickname')
                ->order('c.create_time desc')
                ->group('c.send_uid')
                ->select();
        }

        /*$sql = "select a.* from dp_chat_content_date a
              where create_time = 
              (select max(create_time) from dp_chat_content_date where send_uid = a.send_uid) 
              order by a.create_time 
              ";

        var_dump(Db::query($sql));*/
        $this->assign('chat_res',$chat_res);
        $this->assign('start_uid',UID);
        return $this->fetch();
    }

    public function show(){
        $user_a = Db::name('recharge')->where('uid', UID)->select();
        foreach ($user_a as $k=>$v){
            if($v['recharge_type'] === 'account'){
                $user_a[$k]['recharge_type'] = '余额消费';
            }
            if($v['recharge_type'] === 'weixin'){
                $user_a[$k]['recharge_type'] = '微信消费';
            }
        }
        $user=array_reverse($user_a);
        Db::name('recharge')->where('uid', UID)->update(['read_status' => '1']);
        $this->assign('user',$user);
        return $this->fetch();
    }

    public function vip(){


        $user_a = Db::name('upgrade_member')->where('uid', UID)->select();
        //处理数据
        foreach ($user_a as $k=>$v){
            if($v['recharge_type'] === 'account'){
                $user_a[$k]['recharge_type'] = '余额消费';
            }
            if($v['recharge_type'] === 'weixin'){
                $user_a[$k]['recharge_type'] = '微信消费';
            }
        }
        Db::name('upgrade_member')->where('uid', UID)->update(['read_status' => '1']);
        $user=array_reverse($user_a);
        $this->assign('user',$user);
        return $this->fetch();

    }

}