<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017\12\15 0015
 * Time: 16:42
 */

namespace app\user\home;

use think\Controller;
class News extends Controller
{


    public function _initialize()
    {

        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->assign('title','消息页面');
    }

    public function index(){

        //echo "<script>alert('".lang('Parse error')."')</script>";   //测试语言包助手函数

        return $this->fetch();
    }
}