<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017\12\18 0018
 * Time: 10:07
 */

namespace app\user\home;

use think\Controller;
class ReleaseDetail extends Common
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){

       //判断用户是否有权限查看信息


        return $this->fetch();
    }


}