<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017\12\18 0018
 * Time: 10:07
 */

namespace app\user\home;

use think\Controller;
use app\user\model\home\Privilege;
use think\Db;
class ReleaseDetail extends Common
{

    private static $model ;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        self::$model = new Privilege;
    }

    public function index($id){
       //判断用户是否有权限查看信息
//                 //if(request()->isGet()){
//            //进入详情页面的权限
//            $privilege_list = self::$model->sel_privilege()->allow_priview_list;
//            //青铜权限取消判断
//            /*if($privilege_list == 4 || $privilege_list == 0){
//                //权限不足，直接返回首页或者上一页
//                   $this->redirect(isset($_SERVER['HTTP_REFERER'])?$_SERVER['HTTP_REFERER']:'index/Index/index');
//            }*/
//                //}

       return $this->fetch();
    }


}