<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017\12\18 0018
 * Time: 9:58
 */

namespace app\user\home;

use app\user\home\Common;
use think\Controller;
use think\Db;
class Release extends Common
{


    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){
        return $this->fetch();
    }
    public  function  release()
    {
        $journey = Db::name('user')->where('id', UID)->find();
        if ($journey['birthday'] == null || $journey['nickname'] == null || $journey['autograph'] == null || $journey['real_name'] == null ||  $journey['head_img'] == null || $journey['address'] == null || $journey['qq'] == null || $journey['height'] == null || $journey['interest'] == null || $journey['measurement'] == null || $journey['weight'] == null) {

            return json(false);
        }
        $journey = Db::name('user_release')->where('uid', UID)->select();
        if ($journey) {

            return json(false);
        } else {
            if (request()->post('travel_total_time')==null){
                return json(false);
            }
            $data = $this->get_data();
            $validate = $this->validate($data, 'Release');
            if ($validate != true) {
                return json($validate);
            }else{
                Db::name('user_release')->insert($data);
                return json(true);
            }
        }
    }
    private function get_data(){
        if (request()->post('cyj')==null){
            $data = [
                'uid' => UID,
                'release_object' => request()->post('release_object'),                 //约游对象
                'travel_start_time' => strtotime(request()->post('travel_start_time')),              //出行时间
                'travel_total_time' => request()->post('travel_total_time'),   //出行天数
                'travel_tool' => request()->post('travel_tool'),                    //出行方式
                'create_time' => time(),                         //发布时间
                'is_sincerity' =>'1',                            //是否缴纳滞纳金
            ];
        }else{
            $data = [
                'uid' => UID,
                'release_object' => request()->post('release_object'),                 //约游对象
                'travel_start_time' => strtotime(request()->post('travel_start_time')),              //出行时间
                'travel_total_time' => request()->post('travel_total_time'),   //出行天数
                'travel_tool' => request()->post('travel_tool'),                    //出行方式
                'sincerity_money' => '100',                      //诚意金数额
                'create_time' => time(),                         //发布时间
                'is_sincerity' =>'2',                            //是否缴纳滞纳金
            ];
        }

        return $data;
    }
}