<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017\12\18 0018
 * Time: 9:58
 */

namespace app\user\home;

use app\user\home\Common;
use think\Controller;
use think\Db;
class Release extends Common
{


    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){
        return $this->fetch();
    }
    public  function  release()
    {

        //判断会员是否认证
        $user_identity = Db::name('user_identity')->where('uid',UID)->value('status');
        if($user_identity !== 1){
            return json('会员没有认证,无法发布消息');
        }

            $data = $this->get_data();
            $validate = $this->validate($data, 'Release');
            if ($validate === true) {
                Db::name('user_release')->insert($data);
                return json(true);
            }else{
                return json($validate);
            }

    }
    private function get_data(){
        if (request()->post('cyj')==null){
            $data = [
                'uid' => UID,
                'release_object' => request()->post('release_object'),                 //约游对象
                'travel_start_time' => strtotime(request()->post('travel_start_time')),              //出行时间
                'travel_total_time' => request()->post('travel_total_time'),   //出行天数
                'travel_tool' => request()->post('travel_tool'),                    //出行方式
                'create_time' => time(),                         //发布时间
                'is_sincerity' =>'0',                            //是否缴纳滞纳金
            ];
        }else{
            $data = [
                'uid' => UID,
                'release_object' => request()->post('release_object'),                 //约游对象
                'travel_start_time' => strtotime(request()->post('travel_start_time')),              //出行时间
                'travel_total_time' => request()->post('travel_total_time'),   //出行天数
                'travel_tool' => request()->post('travel_tool'),                    //出行方式
                'sincerity_money' => '100',                      //诚意金数额
                'create_time' => time(),                         //发布时间
                'is_sincerity' =>'1',                            //是否缴纳滞纳金
            ];
        }

        return $data;
    }
}