<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017\12\18 0018
 * Time: 10:52
 */

namespace app\user\home;

use think\Controller;
use think\Db;
class Wallet extends Common
{


    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

    }

    public function index(){

        //显示用户余额
        $this->assign('account_money',Db::name('user')->where('id',UID)->value('account'));
        return $this->fetch();

    }


    public function recharge(){
        return $this->fetch();
    }

}