<?php
// +----------------------------------------------------------------------
// | 海豚PHP框架 [ DolphinPHP ]
// +----------------------------------------------------------------------
// | 版权所有 2016~2017 河源市卓锐科技有限公司 [ http://www.zrthink.com ]
// +----------------------------------------------------------------------
// | 官方网站: http://dolphinphp.com
// +----------------------------------------------------------------------
// | 开源协议 ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------

namespace app\index\controller;
use app\user\model\home\User;
use think\cache\driver\Redis;
use app\user\model\home\User As UserModel;
use think\Session;
use think\Db;

/**
 * 前台首页控制器
 * @package app\index\controller
 */
class Index extends Home
{

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        if(false){
            $this->redirect('user/login/index');
        }
    }

    public function index()
    {


        // 默认跳转模块
        if (config('home_default_module') != 'index') {
            $this->redirect(config('home_default_module'). '/index/index');
        }

        if(intval(request()->param('bindphone')) === 1){
            //提示用户需要绑定手机
            $this->assign('bindphone',intval(1));
        }else{
            $this->assign('bindphone',false);
        }

        /*$config = [
            'host'       => '127.0.0.1',
            'port'       => 6379,
            'password'   => '123456',
            'select'     => 0,
            'timeout'    => 0,
            'expire'     => 0,
            'persistent' => false,
            'prefix'     => '',
        ];

        $Redis=new Redis($config);
        $Redis->set("test","unique");
        echo  $Redis->get("test");*/

        //取出地址
        if(request()->isGet()){


            $user = new User();
            $data = $user->escort_info();

            foreach( $data as $k=>$v1 )
            {

                $birthday_format = isset(getIDCardInfo($v1->id_card_num)['birthday']) ? getIDCardInfo($v1->id_card_num)['birthday']:0;
                //若为系统添加伴游,直接通过伴游生日计算
                if($v1->sys_id === 0){
                    $birthday_format =date('Y',$v1->birthday);
                }
                $a = date('Y', time());
                $b = date('Y', strtotime($birthday_format));    //求出年龄
                $data[$k]['id_card_num'] = $birthday_format ? abs($a - $b) : 0;

                $str=$v1["address"];
                $arr_str=explode(" ",$str);//以空格为拆分条件
                $data[$k]['address'] = $arr_str[0];
            }
            $this->assign('data',$data);
        }
        //获取用户当前位置若未登录则不显示距离

       return $this->fetch();

    }


    public function test(){


       $a = '{
    "name":"重庆",
    "code":"500000",
    "sub": [
      {
        "name": "重庆市",
        "code": "500000",
        "sub":[
            {
              "name":"万州区",
              "code":"500101"
            },
            {
              "name":"涪陵区",
              "code":"500102"
            },
            {
              "name":"渝中区",
              "code":"500103"
            },
            {
              "name":"大渡口区",
              "code":"500104"
            },
            {
              "name":"江北区",
              "code":"500105"
            },
            {
              "name":"沙坪坝区",
              "code":"500106"
            },
            {
              "name":"九龙坡区",
              "code":"500107"
            },
            {
              "name":"南岸区",
              "code":"500108"
            },
            {
              "name":"北碚区",
              "code":"500109"
            },
            {
              "name":"綦江区",
              "code":"500110"
            },
            {
              "name":"大足区",
              "code":"500111"
            },
            {
              "name":"渝北区",
              "code":"500112"
            },
            {
              "name":"巴南区",
              "code":"500113"
            },
            {
              "name":"黔江区",
              "code":"500114"
            },
            {
              "name":"长寿区",
              "code":"500115"
            },
            {
              "name":"江津区",
              "code":"500116"
            },
            {
              "name":"合川区",
              "code":"500117"
            },
            {
              "name":"永川区",
              "code":"500118"
            },
            {
              "name":"南川区",
              "code":"500119"
            },
            {
              "name":"璧山区",
              "code":"500120"
            },
            {
              "name":"铜梁区",
              "code":"500151"
            },
            {
              "name":"潼南县",
              "code":"500223"
            },
            {
              "name":"荣昌县",
              "code":"500226"
            },
            {
              "name":"梁平县",
              "code":"500228"
            },
            {
              "name":"城口县",
              "code":"500229"
            },
            {
              "name":"丰都县",
              "code":"500230"
            },
            {
              "name":"垫江县",
              "code":"500231"
            },
            {
              "name":"武隆县",
              "code":"500232"
            },
            {
              "name":"忠县",
              "code":"500233"
            },
            {
              "name":"开县",
              "code":"500234"
            },
            {
              "name":"云阳县",
              "code":"500235"
            },
            {
              "name":"奉节县",
              "code":"500236"
            },
            {
              "name":"巫山县",
              "code":"500237"
            },
            {
              "name":"巫溪县",
              "code":"500238"
            },
            {
              "name":"石柱土家族自治县",
              "code":"500240"
            },
            {
              "name":"秀山土家族苗族自治县",
              "code":"500241"
            },
            {
              "name":"酉阳土家族苗族自治县",
              "code":"500242"
            },
            {
              "name":"彭水苗族土家族自治县",
              "code":"500243"
            }
        ]
      }
    ]
  }';

      $m = json_decode($a,true);
       echo json_encode($m);

      exit;
    }


    public function ossup(){
        return $this->fetch();
    }

    public function ossserver(){
        //require_once VENDOR_PATH.'/sts-server/sts.php';   //已配置好  windows环境可用
        //调用搭建的服务函数获取临时帐号
      $ossup =  new StsServer();
      $ossup->index();
    }

}
