<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018\4\28 0028
 * Time: 17:26
 */

namespace app\broker\home;

use  app\broker\model\home\BrokerUser;

use think\Db;

class Account extends Common
{

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }


    //个人账户首页
    public function index(){

        //获取该账户的支付宝名称
        $info = BrokerUser::where('ubid',UBID)->field('alipay_num,alipay_name')->find();
        $this->assign('info',$info);
        return $this->fetch();

    }

    //修改支付宝账户名

    public function check(){
        $data = request()->post();

        $result = $this->validate($data,'Account');

        if($result !== true){
            return json(array('code'=>201,'msg'=>$result));
        }
        $data_update = BrokerUser::update($data,['ubid'=>UBID]);

        return json(array('code'=>200,'msg'=>'保存成功'));
    }


    //用户提现
    public function withdraw_to(){
        //查询经纪人用户可以提现的金额
        $broker_model = new BrokerUser();
        $broker_info = $broker_model->sel_broker_info(UBID);
        if(request()->isAjax()){

            $money = request()->post('money');
            if(floatval($money) > floatval($broker_info['account'])){
                return json(array('code'=>404,'msg'=>'金额不足'));
            }else{
                //扣除账户余额
               $re = BrokerUser::where('ubid',UBID)->setDec('account',floatval($money));

               if($re){
                   //记录提现
                   $data = array(
                       'ubid'=>UBID,
                       'withdrawals'=>floatval($money),
                       'create_time'=>request()->time()
                   );
                   Db::name('user_broker_withdraw')->insert($data);
                   return json(array('code'=>200,'msg'=>'提现申请成功'));
               }
            }
        }

        $this->assign('broker_info',$broker_info);
        return $this->fetch();
    }
}