<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018\4\25 0025
 * Time: 16:07
 */

namespace app\broker\home;

use think\Controller;

use app\broker\model\home\Login;
class Common extends Controller
{

    protected  function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        defined('UBID') or define('UBID', $this->isLogin());
    }


    /**
     * 检查是否登录，没有登录则跳转到登录页面
     * @return int
     */
    final protected function isLogin()
    {
        // 判断是否登录
        $login_model = new Login();
        if ($uid = $login_model->auto_login()) {
            // 已登录
            return $uid;
        } else {
            // 未登录
            $this->redirect('broker/Login/index');
        }
    }

}