<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018\4\28 0028
 * Time: 16:48
 */

namespace app\broker\home;


class Help extends Common
{

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }


    public function index(){
        return $this->fetch();
    }
}