<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018\4\25 0025
 * Time: 11:29
 */

namespace app\broker\home;

use think\Controller;
use app\broker\model\home\Login AS LoginModel;
use think\Session;
class Login extends  Controller
{


    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

    }

    public function index(){
        return $this->fetch();
    }

    /*
     * 用户登录
     * */
    public function check(){
        if(request()->isAjax()){
            $data = $this->get_data();
            $model = new LoginModel();
           return  $model->login($data);
        }
    }

    /*
     * 获取数据
     * */
    private function get_data(){
        $data = [];
        $data['phone'] = request()->post('mobile_phone');
        $data['password']  = md5(request()->post('password'));
        return $data;
    }


    /*
     * 用户退出登录
     * */
    public function login_out(){
        Session::delete('broker_user_auth_home' );
        Session::delete('broker_user_auth_sign_home');
        //记录cookie 有效期内可自动登录
        cookie('broker_uid_home', null);
        cookie('broker_signin_token_home', null);
        $this->redirect('broker/Login/index');
    }

}