<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018\4\26 0026
 * Time: 17:21
 */

namespace app\broker\home;

use app\broker\model\home\BrokerUser;
use think\Db;

class MyInfo extends  Common
{

    /*
     * 个人资料页面
     * */
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }



    public function index(){
        //个人资料首页
        $broker_model = new BrokerUser();

        $info = $broker_model->sel_broker_info(UBID);

        $this->assign('info',$info);
        return $this->fetch();

    }

    /*
     * 个人资料修改页面
     * */

    public function check(){
        $data = $this->get_data();
        $validate = $this->validate($data, 'MyInfo');
        if($validate !== true){
            //验证没通过
            return json(array('code'=>201,'msg'=>$validate));
        }else{
            //验证通过
            //修改数据
            BrokerUser::where('ubid',UBID)->update($data);

            return json(array('code'=>200,'msg'=>'保存成功'));

        }

    }

    private function  get_data(){

        $data =array();
        $data['username'] = trim(request()->post('username'));

        $data['email'] = trim(request()->post('email'));

        $data['sex']  = request()->post('sex');
        return $data;
    }

    //我的分销记录
    /*
    * return 按月份统计的数据
    * */
    public function sale_record(){

        //$record = Db::name('broker_sales_record')->where('buid',UBID)->find();

        $sql_record = function($year = 2018 ,$month = 0){
           return  "select DATE_FORMAT(FROM_UNIXTIME(create_time),'%Y-%m') as months,buid,id,get_money,create_time
                    from dp_broker_sales_record 
                    where buid = ".UBID." AND YEAR(FROM_UNIXTIME(create_time)) = $year 
                    AND  MONTH(FROM_UNIXTIME(create_time))= $month
                    ";
        };

        $broker_model = new BrokerUser();

        if(request()->isGet()){
            //查选相关年份的记录，按月统计
            $year = date("Y",time());//显示当前默认年月
            $month = date("m",time());//显示当前默认年月
            $this->assign('year',$year);
            $this->assign('month',$month);
            $this->assign('year_month',date("Y-m",time()));
            return $this->fetch();
        }

        if(request()->isAjax()){
            //ajax请求数据
            $year_month = request()->post('year');
            if(strpos($year_month,'-')){
                $r_year = substr($year_month,0,strpos($year_month,'-'));
                $r_month = substr($year_month,strpos($year_month,'-')+1);
            }else{
                $r_year = request()->post('year');
                $r_month = request()->post('month');
            }
            $money_take = $broker_model->broker_withdraw(UBID,$r_year,$r_month);
            return json(
                array(
                    'record'=>Db::query($sql_record($r_year,$r_month)),
                    'money_take'=>$money_take,
                )
            );
        }
    }
}