<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018\5\7 0007
 * Time: 11:15
 */

namespace app\broker\home;

use app\broker\model\home\BrokerUser;
use think\Db;
class Withdraw extends Common
{


    /*
     * 可提现页面
     * */

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){

        //查询我的收入

        $broker_model = new BrokerUser();
        if(request()->isGet()){
            $my_account = $broker_model->sel_broker_info(UBID)['account'];
            $this->assign('my_account',$my_account);
            //查询注册明细人数
            $people_num = Db::name('broker_sales_record')->where('buid = '.UBID)->count('id');
            $this->assign('people_num',$people_num);
            //查询该经纪人推销注册的用户
            $sign_user = Db::name('broker_sales_record')
                        ->alias('br')
                        ->where('buid = '.UBID)
                        ->join('user u','br.uid = u.id')
                        ->field('u.nickname,u.sys_id,br.create_time,br.get_money')
                        ->select();
            $this->assign('sign_user',$sign_user);
            return $this->fetch();
        }

    }
}