<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018\4\8 0008
 * Time: 16:10
 */
namespace app\push\home;
use think\Controller;
use app\user\home\Common;
//use GatewayWorker\Lib\Gateway;
use GatewayClient\Gateway;
use think\cache\driver\Redis;
class Index  extends Common
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        session('uid', UID);
    }

    public function hello() {
        $uid = $_GET['uid'];

        return $this->fetch();
    }

    public function BindClientId() {

        $client_id = $_POST['client_id'];
        // 设置GatewayWorker服务的Register服务ip和端口，请根据实际情况改成实际值
        Gateway::$registerAddress = '127.0.0.1:1238';

        $bindUid = session('uid');
        // 假设用户已经登录，用户uid和群组id在session中
        // client_id与uid绑定
        Gateway::bindUid($client_id, $bindUid);
        $message = isset($_POST['message'])?$_POST['message']:"";

        $uid = isset($_POST['uid'])?$_POST['uid']:'';
        //若进入聊天页面传入uid则进行分组绑定
        if($uid){
            ///Gateway::sendToUid($uid,json_encode($message));
            // 加入某个群组（可调用多次加入多个群组）
            if($bindUid > $uid){
                $str = $uid.'-'.$bindUid;
            }else{
                $str = $bindUid.'-'.$uid;
            }
            Gateway::joinGroup($client_id, $str);
        }
        //Gateway::sendToGroup($str,json_encode($message));
    }

    public function AjaxSendMessage() {
        $message = $_POST['message'];
        $uid = $_POST['uid'];
        // 设置GatewayWorker服务的Register服务ip和端口，请根据实际情况改成实际值
        Gateway::$registerAddress = '127.0.0.1:1238';

        //GateWay::sendToUid($uid,json_encode($message));
        $bindUid = UID;
        if($bindUid > $uid){
            $str = $uid.'-'.$bindUid;
        }else{
            $str = $bindUid.'-'.$uid;
        }

       $config = [
            'host'       => '127.0.0.1',
            'port'       => 6379,
            'password'   => '123456',
            'select'     => 0,
            'timeout'    => 0,
            'expire'     => 0,
            'persistent' => false,
            'prefix'     => '',
        ];

        $Redis=new Redis($config);
        $Redis->set("test","我的redis玩的是相当的溜的啊");
        echo  $Redis->get("test");

        GateWay::sendToGroup($str,json_encode(array('send_uid'=>UID,'message'=>$message)));
        Gateway::sendToUid($uid,json_encode($message));
    }
}